[package]
name = "embassy-net"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2018"

[features]
std = []
defmt-trace = []
defmt-debug = []
defmt-info = []
defmt-warn = []
defmt-error = []

[dependencies]
defmt = { version = "0.1.3", optional = true }
log = { version = "0.4.11", optional = true }
embassy             = { version = "0.1.0" }
managed             = { version = "0.8.0", default-features = false, features = [ "map" ]}
heapless            = { version = "0.5.6", default-features = false }
as-slice            = { version = "0.1.4" }
generic-array       = { version = "0.14.4", default-features = false }
stable_deref_trait  = { version = "1.2.0", default-features = false }
futures             = { version = "0.3.5", default-features = false, features = [ "async-await" ]}

[dependencies.smoltcp]
version = "0.6.0"
# git = "https://github.com/akiles/smoltcp"
# rev = "00952e2c5cdf5667a1dfb6142258055f58d3851c"
default-features = false
features = [
  "medium-ethernet",
  "medium-ip",
  "proto-ipv4",
  "proto-dhcpv4",
  #"proto-igmp",
  #"proto-ipv6",
  #"socket-raw",
  #"socket-icmp",
  #"socket-udp",
  "socket-tcp",
  "async",
]
